/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grpassignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;  
import java.util.Date;  

/**
 *
 * @author LENOVO
 */
public class AdminHomepage extends javax.swing.JFrame {

    SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");  
    SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");  
    Date date = new Date();
    
    public AdminHomepage() {
        initComponents();
        
        date_time.setText(dateFormatter.format(date));
         try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            
            Statement st = con.createStatement();
            String sql = "SELECT * FROM Vehicle";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String id = rs.getNString("car_id");
               String model = rs.getNString("model");
               String owner = rs.getNString("owner_name");
               String tbData[] = {id, model, owner};
               DefaultTableModel tblModel = (DefaultTableModel)adminTable.getModel();
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vehicle = new javax.swing.JButton();
        greencar = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        date_time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        update_Button = new javax.swing.JButton();
        delete_Button = new javax.swing.JButton();
        insert_Button = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        platenum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        carmodel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        carowner = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cars");
        setSize(new java.awt.Dimension(1365, 960));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Screenshot 2022-10-16 153406.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        vehicle.setBackground(new java.awt.Color(204, 204, 255));
        vehicle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        vehicle.setText("VEHICLE RECORDS");
        vehicle.setToolTipText("");
        vehicle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleActionPerformed(evt);
            }
        });

        greencar.setBackground(new java.awt.Color(204, 204, 255));
        greencar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        greencar.setText("GREENCAR RECORDS");
        greencar.setToolTipText("");
        greencar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        greencar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greencarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greencar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greencar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        title.setText("VEHICLE RECORDS");

        date_time.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        date_time.setText("15 / 10 / 2022 ");

        adminTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLATE NUMBER", "MODEL", "OWNER NAME"
            }
        ));
        adminTable.setRowHeight(25);
        adminTable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        adminTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        adminTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminTable);
        adminTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        update_Button.setBackground(new java.awt.Color(255, 204, 0));
        update_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        update_Button.setForeground(new java.awt.Color(255, 255, 255));
        update_Button.setText("UPDATE");
        update_Button.setToolTipText("");
        update_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ButtonActionPerformed(evt);
            }
        });

        delete_Button.setBackground(new java.awt.Color(255, 0, 0));
        delete_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_Button.setText("DELETE");
        delete_Button.setToolTipText("");
        delete_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });

        insert_Button.setBackground(new java.awt.Color(0, 153, 0));
        insert_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        insert_Button.setForeground(new java.awt.Color(255, 255, 255));
        insert_Button.setText("INSERT");
        insert_Button.setToolTipText("");
        insert_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_ButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(204, 204, 204));
        searchButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 51, 153));
        searchButton.setText("SEARCH");
        searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        platenum.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        platenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platenumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("PLATE NUMBER");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("MODEL");

        carmodel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        carmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carmodelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("OWNER NAME");

        carowner.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        carowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carownerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(carowner)
                                            .addComponent(carmodel)
                                            .addComponent(platenum, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))))
                                .addGap(26, 26, 26)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(title))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_time)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_time, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(platenum, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(carmodel)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(carowner)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ButtonActionPerformed
        // TODO add your handling code here:
           try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);           
            String sql = "";
            sql = "UPDATE Vehicle SET car_id=?, model=?, owner_name=? WHERE (car_id = "+platenum.getText()+")";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, platenum.getText());
            pst.setString(2, carmodel.getText());
            pst.setString(3, carowner.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Successfully Updated");
            
            platenum.setText("");
            carmodel.setText("");
            carowner.setText("");
            DefaultTableModel tblModel = (DefaultTableModel)adminTable.getModel();
            tblModel.setRowCount(0);
            Statement st = con.createStatement();
            sql = "SELECT * FROM Vehicle";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String id = rs.getNString("car_id");
               String model = rs.getNString("model");
               String owner = rs.getNString("owner_name");
               platenum.setText(id);
               carmodel.setText(model);
               carowner.setText(owner);
               String tbData[] = {id, model, owner};
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Could not be Updated");
            System.out.println(e);
        }
    }//GEN-LAST:event_update_ButtonActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        // TODO add your handling code here:
           try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);           
            String sql = "";
            sql = "DELETE FROM Vehicle WHERE (car_id = "+platenum.getText()+")";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Successfully Deleted");
            
            platenum.setText("");
            carmodel.setText("");
            carowner.setText("");
            DefaultTableModel tblModel = (DefaultTableModel)adminTable.getModel();
            tblModel.setRowCount(0);
            Statement st = con.createStatement();
            sql = "SELECT * FROM Vehicle";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String id = rs.getNString("car_id");
               String model = rs.getNString("model");
               String owner = rs.getNString("owner_name");
               String tbData[] = {id, model, owner};
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Could not be Deleted");
            System.out.println(e);
        }
    }//GEN-LAST:event_delete_ButtonActionPerformed

    private void vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleActionPerformed

    private void greencarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greencarActionPerformed
        // TODO add your handling code here:
        new GreenCarHomepage().setVisible(true);
        new AdminHomepage().setVisible(false);
    }//GEN-LAST:event_greencarActionPerformed

    private void insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_ButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String sql = "INSERT INTO Vehicle(car_id, model, owner_name) VALUES(?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, platenum.getText());
            pst.setString(2, carmodel.getText());
            pst.setString(3, carowner.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record Successfully Added!");
            
            platenum.setText("");
            carmodel.setText("");
            carowner.setText("");
            DefaultTableModel tblModel = (DefaultTableModel)adminTable.getModel();
            tblModel.setRowCount(0);
            Statement st = con.createStatement();
            sql = "SELECT * FROM Vehicle";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String id = rs.getNString("car_id");
               String model = rs.getNString("model");
               String owner = rs.getNString("owner_name");
               String tbData[] = {id, model, owner};
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Could not be Added, Vehicle with Plate number already exists");
            System.out.println(e);
        }
    }//GEN-LAST:event_insert_ButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);           
            Statement st = con.createStatement();
            String sql = "";
            sql = "SELECT * FROM Vehicle WHERE (car_id = "+platenum.getText()+")";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String id = rs.getNString("car_id");
               String model = rs.getNString("model");
               String owner = rs.getNString("owner_name");
               platenum.setText(id);
               carmodel.setText(model);
               carowner.setText(owner);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No such vehicle could be found");
            System.out.println(e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void platenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platenumActionPerformed

    private void carownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carownerActionPerformed

    private void carmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carmodelActionPerformed

    private void adminTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)adminTable.getModel();
        int selectedRowIndex = adminTable.getSelectedRow();
        
        platenum.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
        carmodel.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
        carowner.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_adminTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminTable;
    private javax.swing.JTextField carmodel;
    private javax.swing.JTextField carowner;
    private javax.swing.JLabel date_time;
    private javax.swing.JButton delete_Button;
    private javax.swing.JButton greencar;
    private javax.swing.JButton insert_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField platenum;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel title;
    private javax.swing.JButton update_Button;
    private javax.swing.JButton vehicle;
    // End of variables declaration//GEN-END:variables
}
