package grpassignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;  
import java.util.Date;

public class GreenCarHomepage extends javax.swing.JFrame {

    /** Creates new form GreenCarHomepage */
    
    SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");  
    SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");  
    Date date = new Date();
    
    public GreenCarHomepage() {
        initComponents();
        
        date_time1.setText(dateFormatter.format(date));
         try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            
            Statement st = con.createStatement();
            String sql = "SELECT * FROM Green";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String recordDate = rs.getNString("record_date");
               String id = rs.getNString("car_id");
               String electric = String.valueOf(rs.getDouble("electrical_distance"));
               String total = String.valueOf(rs.getDouble("total_distance"));
               String co2 = String.valueOf(rs.getDouble("co2_reduction"));
               String battery = String.valueOf(rs.getInt("endBattery"));
               
               String tbData[] = {recordDate, id, electric, total, co2, battery};
               DefaultTableModel tblModel = (DefaultTableModel)greenTable.getModel();
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        searchComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        first_name = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        update_Button = new javax.swing.JButton();
        delete_Button = new javax.swing.JButton();
        insert_Button = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        date_time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vehicle = new javax.swing.JButton();
        greencar = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        greenTable = new javax.swing.JTable();
        platenum = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        insertBn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        date_time1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        electricDistance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalDistance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        co2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        battery = new javax.swing.JTextField();
        recordDate = new javax.swing.JTextField();

        title.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        title.setText("VEHICLE RECORDS");

        searchComboBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLATE NUMBER", "DATE", "MODEL ", "OWNER NAME" }));

        adminTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "PLATE NUMBER", "MODEL", "OWNER NAME", "ELETRICAL DISTANCE COVERED", "TOTAL DISTANCE COVERED", "CO2 REDUCTION %", "ELECTRICAL BATTERY"
            }
        ));
        adminTable.setRowHeight(25);
        adminTable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        adminTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(adminTable);

        first_name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        update_Button.setBackground(new java.awt.Color(255, 204, 0));
        update_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        update_Button.setForeground(new java.awt.Color(255, 255, 255));
        update_Button.setText("UPDATE");
        update_Button.setToolTipText("");
        update_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ButtonActionPerformed(evt);
            }
        });

        delete_Button.setBackground(new java.awt.Color(255, 0, 0));
        delete_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_Button.setText("DELETE");
        delete_Button.setToolTipText("");
        delete_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });

        insert_Button.setBackground(new java.awt.Color(0, 153, 0));
        insert_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        insert_Button.setForeground(new java.awt.Color(255, 255, 255));
        insert_Button.setText("INSERT");
        insert_Button.setToolTipText("");
        insert_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_ButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(204, 204, 204));
        searchButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 51, 153));
        searchButton.setText("SEARCH");
        searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        date_time.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        date_time.setText("15 / 10 / 2022 ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setSize(new java.awt.Dimension(1370, 960));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Screenshot 2022-10-16 153406.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        vehicle.setBackground(new java.awt.Color(204, 204, 255));
        vehicle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        vehicle.setText("VEHICLE RECORDS");
        vehicle.setToolTipText("");
        vehicle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleActionPerformed(evt);
            }
        });

        greencar.setBackground(new java.awt.Color(204, 204, 255));
        greencar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        greencar.setText("GREENCAR RECORDS");
        greencar.setToolTipText("");
        greencar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        greencar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greencarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greencar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greencar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        title1.setText("GREENCAR RECORDS");

        greenTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        greenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "PLATE NUMBER", "ELETRICAL DISTANCE COVERED", "TOTAL DISTANCE COVERED", "CO2 REDUCTION %", "ELECTRICAL BATTERY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        greenTable.setRowHeight(25);
        greenTable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        greenTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        greenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(greenTable);

        platenum.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        platenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platenumActionPerformed(evt);
            }
        });

        jPanel3.setForeground(new java.awt.Color(204, 255, 204));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        deleteBtn.setToolTipText("");
        deleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(204, 204, 204));
        searchBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 51, 153));
        searchBtn.setText("SEARCH");
        searchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        insertBn.setBackground(new java.awt.Color(0, 153, 0));
        insertBn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        insertBn.setForeground(new java.awt.Color(255, 255, 255));
        insertBn.setText("INSERT");
        insertBn.setToolTipText("");
        insertBn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        insertBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(255, 204, 0));
        updateBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.setToolTipText("");
        updateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertBn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        date_time1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        date_time1.setText("15 / 10 / 2022 ");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("PLATE NUMBER");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("DATE");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("ELECTRICAL DISTANCE");

        electricDistance.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        electricDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricDistanceActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("TOTAL DISTANCE");

        totalDistance.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        totalDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDistanceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setText("CO2 REDUCTION %");

        co2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        co2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setText("BATTERY %");

        battery.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        battery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batteryActionPerformed(evt);
            }
        });

        recordDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        recordDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(platenum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(electricDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(recordDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30)
                                        .addComponent(co2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(105, 105, 105)
                                        .addComponent(battery, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(title1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(date_time1)
                                .addGap(30, 30, 30))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_time1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(title1)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(co2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(battery, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(recordDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(platenum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(electricDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(418, 418, 418))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleActionPerformed
        // TODO add your handling code here:
        new AdminHomepage().setVisible(true);
        new GreenCarHomepage().setVisible(false);
    }//GEN-LAST:event_vehicleActionPerformed

    private void greencarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greencarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greencarActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private void update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_ButtonActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_ButtonActionPerformed

    private void insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_ButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void platenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platenumActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
           try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);           
            String sql = "";
            sql = "DELETE FROM Green WHERE (record_date='"+recordDate.getText()+"' AND car_id ='"+platenum.getText()+"')";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Successfully Deleted");
            
            recordDate.setText("");
            platenum.setText("");
            electricDistance.setText("");
            totalDistance.setText("");
            co2.setText("");
            battery.setText("");
            DefaultTableModel tblModel = (DefaultTableModel)greenTable.getModel();
            tblModel.setRowCount(0);
            Statement st = con.createStatement();
            sql = "SELECT * FROM Green";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String recordDate = rs.getNString("record_date");
               String id = rs.getNString("car_id");
               String electric = String.valueOf(rs.getDouble("electrical_distance"));
               String total = String.valueOf(rs.getDouble("total_distance"));
               String co2 = String.valueOf(rs.getDouble("co2_reduction"));
               String battery = String.valueOf(rs.getInt("endBattery"));
               
               String tbData[] = {recordDate, id, electric, total, co2, battery};
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Could not be Deleted");
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            String recordedDate = recordDate.getText();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);           
            Statement st = con.createStatement();
            String sql = "";
            sql = "SELECT * FROM Green WHERE (record_date='"+recordedDate+"' AND car_id ='"+platenum.getText()+"') ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String rDate = rs.getNString("record_date");
               String id = rs.getNString("car_id");
               Double eDistance = rs.getDouble("electrical_distance");
               Double enDistance = rs.getDouble("total_distance");
               Double emission = rs.getDouble("co2_reduction");
               int endBattery = rs.getInt("endBattery");
               recordDate.setText(rDate);
               platenum.setText(id);
               electricDistance.setText(Double.toString(eDistance));
               totalDistance.setText(Double.toString(enDistance));
               co2.setText(Double.toString(emission));
               battery.setText(Integer.toString(endBattery));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No such vehicle could be found");
            System.out.println(e);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void greenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)greenTable.getModel();
        int selectedRowIndex = greenTable.getSelectedRow();
        
        recordDate.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
        platenum.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
        electricDistance.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
        totalDistance.setText(tblModel.getValueAt(selectedRowIndex, 3).toString());
        co2.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
        battery.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_greenTableMouseClicked

    private void recordDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordDateActionPerformed

    private void totalDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDistanceActionPerformed

    private void electricDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electricDistanceActionPerformed

    private void batteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batteryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batteryActionPerformed

    private void co2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_co2ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String sql = "";
            sql = "UPDATE Green SET electrical_distance=?, total_distance=?, co2_reduction=?, endBattery=? WHERE (record_date='"+recordDate.getText()+"' AND car_id ='"+platenum.getText()+"')";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setDouble(1, Double.parseDouble(electricDistance.getText()));
            pst.setDouble(2, Double.parseDouble(totalDistance.getText()));
            pst.setDouble(3, Double.parseDouble(co2.getText()));
            pst.setInt(4, Integer.parseInt(battery.getText()));
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record Successfully Updated");

            recordDate.setText("");
            platenum.setText("");
            electricDistance.setText("");
            totalDistance.setText("");
            co2.setText("");
            battery.setText("");
            DefaultTableModel tblModel = (DefaultTableModel)greenTable.getModel();
            tblModel.setRowCount(0);
            Statement st = con.createStatement();
            sql = "SELECT * FROM Green";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
               String recordDate = rs.getNString("record_date");
               String id = rs.getNString("car_id");
               String electric = String.valueOf(rs.getDouble("electrical_distance"));
               String total = String.valueOf(rs.getDouble("total_distance"));
               String co2 = String.valueOf(rs.getDouble("co2_reduction"));
               String battery = String.valueOf(rs.getInt("endBattery"));
               
               String tbData[] = {recordDate, id, electric, total, co2, battery};
               tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Could not be Updated");
            System.out.println(e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void insertBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBnActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-HHI8NQO:1433;databaseName=GreenCar;encrypt=true;trustServerCertificate=true;integratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String sql = "INSERT INTO Green(record_date, car_id, electrical_distance, total_distance, co2_reduction, endBattery) VALUES(?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, recordDate.getText());
            pst.setString(2, platenum.getText());
            pst.setDouble(3, Double.parseDouble(electricDistance.getText()));
            pst.setDouble(4, Double.parseDouble(totalDistance.getText()));
            pst.setDouble(5, Double.parseDouble(co2.getText()));
            pst.setInt(6, Integer.parseInt(battery.getText()));
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record Successfully Added!");

            recordDate.setText("");
            platenum.setText("");
            electricDistance.setText("");
            totalDistance.setText("");
            co2.setText("");
            battery.setText("");
            DefaultTableModel tblModel = (DefaultTableModel)greenTable.getModel();
            tblModel.setRowCount(0);
            Statement st = con.createStatement();
            sql = "SELECT * FROM Green";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                String recordDate = rs.getNString("record_date");
                String id = rs.getNString("car_id");
                String electric = String.valueOf(rs.getDouble("electrical_distance"));
                String total = String.valueOf(rs.getDouble("total_distance"));
                String co2 = String.valueOf(rs.getDouble("co2_reduction"));
                String battery = String.valueOf(rs.getInt("endBattery"));

                String tbData[] = {recordDate, id, electric, total, co2, battery};
                tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Could not be Added");
            System.out.println(e);
        }
    }//GEN-LAST:event_insertBnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GreenCarHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GreenCarHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GreenCarHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GreenCarHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GreenCarHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminTable;
    private javax.swing.JTextField battery;
    private javax.swing.JTextField co2;
    private javax.swing.JLabel date_time;
    private javax.swing.JLabel date_time1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton delete_Button;
    private javax.swing.JTextField electricDistance;
    private javax.swing.JTextField first_name;
    private javax.swing.JTable greenTable;
    private javax.swing.JButton greencar;
    private javax.swing.JButton insertBn;
    private javax.swing.JButton insert_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField platenum;
    private javax.swing.JTextField recordDate;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchComboBox;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField totalDistance;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton update_Button;
    private javax.swing.JButton vehicle;
    // End of variables declaration//GEN-END:variables

}
